name: C++ Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install g++
        run: sudo apt update && sudo apt install -y g++

      - name: Compile the program
        run: g++ -Wall -o bank_app driver.cpp bank.cpp

      - name: Run the application with predefined input
        run: echo -e "1\n123\nJohn Doe\n1000\n8\n" | ./bank_app
