name: C++ CI

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Compile Code
        run: g++ -o bank_system main.cpp bank.cpp -std=c++11

      - name: Run Tests
        run: ./bank_system
